/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JOptionPane;

/**
 *
 * @author vektorel
 */
public class frmLogin extends javax.swing.JFrame {

    int denemesayisi=0;
    /**
     * Creates new form frmLogin
     */
    public frmLogin() {
        initComponents();
        denemesayisi=0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtkullaniciadi = new javax.swing.JTextField();
        txtsifre = new javax.swing.JPasswordField();
        btngiris = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Kullanıcı Adı");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 27, -1, -1));

        jLabel2.setText("Şifre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));
        getContentPane().add(txtkullaniciadi, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 21, 167, -1));
        getContentPane().add(txtsifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 74, 167, -1));

        btngiris.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        btngiris.setForeground(new java.awt.Color(51, 102, 255));
        btngiris.setText("Giriş");
        btngiris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngirisActionPerformed(evt);
            }
        });
        getContentPane().add(btngiris, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 112, 111, 49));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btngirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngirisActionPerformed
       String kullaniciadi = "admin"; 
       String sifre ="123";
       
       if(txtkullaniciadi.getText().equalsIgnoreCase(kullaniciadi) && txtsifre.getText().equalsIgnoreCase(sifre)){
         frmEvrakKayit frmac = new frmEvrakKayit();
         frmac.show();
       }
       else
       {
           denemesayisi++;
           if(denemesayisi>3){
               JOptionPane.showMessageDialog(null, "3 Defa Şifreyi Yanlış Girdiniz Program Kapanacaktır.");
               System.exit(0);
           }
           else{
               JOptionPane.showMessageDialog(null, denemesayisi+". Deneme!! Kullanıcı Adı ya da Şifre Hatalı Tekrar Deneyiniz.");
           }
           
       }
        
    }//GEN-LAST:event_btngirisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btngiris;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtkullaniciadi;
    private javax.swing.JPasswordField txtsifre;
    // End of variables declaration//GEN-END:variables
}
